-- Workout plan templates.
--
-- Adds:
--   1. profiles.active_template_id — text id of the selected template
--      (e.g. "ppl-6day"). Nullable: NULL means the user hasn't picked
--      yet, which triggers the picker modal on first /workout visit.
--   2. user_workout_exercises (idempotent) — the per-user customization
--      table that already exists in the running DB but was never checked
--      into migrations. Recreated here as `create table if not exists`
--      so fresh environments line up with production.
--
-- Existing users (created before this migration) are backfilled to
-- "custom-6day" so their experience is unchanged.

-- ─── profiles.active_template_id ─────────────────────────────────────────────
alter table public.profiles
  add column if not exists active_template_id text;

-- Backfill: every existing onboarded user gets the original 6-day split.
update public.profiles
   set active_template_id = 'custom-6day'
 where active_template_id is null
   and onboarded_at is not null;

-- ─── user_workout_exercises (idempotent) ─────────────────────────────────────
create table if not exists public.user_workout_exercises (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  mode          text not null check (mode in ('home','gym')),
  day_index     int  not null check (day_index between 0 and 5),
  position      int  not null default 0,
  catalog_id    text,
  name          text not null,
  sets          text not null default '3 x 10',
  note          text,
  images        text[],
  search_query  text,
  created_at    timestamptz not null default now()
);

create index if not exists user_workout_exercises_user_mode_idx
  on public.user_workout_exercises(user_id, mode, day_index, position);

alter table public.user_workout_exercises enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'user_workout_exercises'
       and policyname = 'own workout exercises read'
  ) then
    create policy "own workout exercises read"
      on public.user_workout_exercises for select using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'user_workout_exercises'
       and policyname = 'own workout exercises write'
  ) then
    create policy "own workout exercises write"
      on public.user_workout_exercises for insert with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'user_workout_exercises'
       and policyname = 'own workout exercises update'
  ) then
    create policy "own workout exercises update"
      on public.user_workout_exercises for update using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'user_workout_exercises'
       and policyname = 'own workout exercises delete'
  ) then
    create policy "own workout exercises delete"
      on public.user_workout_exercises for delete using (auth.uid() = user_id);
  end if;
end $$;
