create table if not exists public.user_workout_exercises (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('home','gym')),
  day_index int not null check (day_index between 0 and 5),
  position int not null default 0,
  catalog_id text,
  name text not null,
  sets text not null default '3 x 10',
  note text,
  images text[],
  search_query text,
  created_at timestamptz not null default now()
);

create index if not exists user_workout_exercises_user_mode_day_idx
  on public.user_workout_exercises (user_id, mode, day_index, position);

alter table public.user_workout_exercises enable row level security;

drop policy if exists "own rows select" on public.user_workout_exercises;
create policy "own rows select" on public.user_workout_exercises
  for select using (auth.uid() = user_id);

drop policy if exists "own rows insert" on public.user_workout_exercises;
create policy "own rows insert" on public.user_workout_exercises
  for insert with check (auth.uid() = user_id);

drop policy if exists "own rows update" on public.user_workout_exercises;
create policy "own rows update" on public.user_workout_exercises
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "own rows delete" on public.user_workout_exercises;
create policy "own rows delete" on public.user_workout_exercises
  for delete using (auth.uid() = user_id);
